### ISSUE TITLE
TODO for expo

### ISSUE THREAD

**Issue by IllustratedMan-code** [quaternary-game/quaternary#57]
# All the stuff we need to do before the expo + assignments
- [ ] Close all remaining issues
- [x] add music + sound effects @adediu25 
- [x] Level 1 of main game @john-whiting + @IllustratedMan-code
  - [x] redesign drag n drop menu @IllustratedMan-code 
  - [x] Death when no calories @john-whiting 
  - [x] Reproduction trait @john-whiting 
  - [x] Sight trait 
  - [x] Predator/prey trait (maybe use herbivore/carnivore trait?)
  - [x] Create any needed assets @IllustratedMan-code 
  - [x] Win condition/Lose condition/Objective of first level
- [x] Tutorials @ConnorMcKinney99 
  - [x] Mutation minigame tutorial
  - [x] Codon minigame tutorial
  - [x] Punnett square minigame tutorial
  - [x] Main game tutorial 
- [x] Various UI Fixes and improvements @ConnorMcKinney99 @adediu25 
  - [x] Mutation Master needs a pause button
  - [x] mutation master needs a real end screen
- [ ]  Fill out hours
